### ISSUE TITLE
[MDR] Feedback - Facility-based MDR Form

### ISSUE THREAD

**Issue by charl3sj** [OpenCHS/unicef-moha#1]
- Instead of MCTS it should be RCH Number and restriction for no of digits 
- Validation: Date of Death should always be greater or equal to Date of admission
- Duration of Hospital stay should be automatically calculated from above Date of death and Date of admission
- Whether the mother was admitted in ICU? - Yes - No 
-- If Yes, Duration of ICU stay Days Hours
-- If No, - ICU was Not Required - HDU/Obs ICU Not Available - HDU/Obs ICU Bed Not Available
- 1.G should come before 1.e; if ans in 1.g is 1,2,5 then option Question 1.e not applicable
- Date and Time of delivery to be added only for those where 1e is applicable
- 1E to be auto-calculated based on D/o Admission and D/o Delivery
- 1F to be auto-calculated based on D/o Admission and D/o Death
- In 2B, The Para can not be more than Gravida . Para + Abortion not more than Gravida. Number of living children not more than Para and Gravida
- If 1G is 3,4 then in 2C only 5,6,7 is applicable. If 1.G is 1,2,5 then 2C only 1,2,3,4 applicable
- Ask 3b 'n' no. of times based on answer of 3a
- In 3b, add validation to check Date of admission is in ascending order (maybe add counselling advice/tip that indicates to the user to do so)
- 3b: Change wording of 2nd row to "Date and Time for any complication developed in the facility"
- 3b, third row: Split the questions 1) Time of Calling for transport 2)Time of arrival to this facility
- 3b: 4th row: Type of transport used to reach facility X  -  1) 108 2) 104 3) inter-facility 4) Own Vehicle 5) Hired Vehicle 6) Others Specify
- 3b: 5th row: Time to reach from Facility A to Facility B
- 3b: 6th row: Money spent ----"----
- 3b: Reason for referral - 1) HR Not available 2) Specialist Not Available 3) Blood Not Available, 4) ICU not available, 5) Facility not equipped to manage, 6) Patients/Attendants request, 7) Others Specify
- 3b: Treatment given - Medicines -Fluids -Blood -Oxygen -ICU -Ventilator -Surgery -No treatment given -Others Specify
---

- Section 2 to be show only if ans in 1G is Abortion
- Section 2 - Q. (a) - Show i and ii depending on answer to 2a
- Section 2 - Q (d) - Answer to be made numeric datatype

**Comment by charl3sj** [comment]
@garimadosar5 Please do verify if it can be assumed that Mother will move linearly from Facility 1 -> Facility 2 -> Facility 3 or we should be trying to handle the case of going to/coming from Home in between.

Also validation required for RCH No.

**Comment by charl3sj** [comment]
@garim

**Comment by garimadosar5** [comment]
##### QA Comments - 30 Aug 19
- RCH Validation - 12 digits.
- Also, add RCH validation in the enrolment form.
- If the date of death is before the date of admission, the error message should be `Date of death cannot be before the date of admission`.
- If 1G is 3,4 then in 2C options 4,5,6,7 should be applicable.
