### ISSUE TITLE
[MDSR][Report] Pie chart for Period of death - CBMD

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#10]
##### Description - 
List/Pie chart of the deaths happened at different periods of pregnancy/childbirth from Community based Maternal deaths (Section I (Background Information) - Question 5, Period of death )

##### Data Required - 
- During Pregnancy 
> Number of deaths happened during Pregnancy
- During Delivery
> Number of deaths happened during Delivery
- Within 42 days after delivery
> Number of deaths happened within 42 days after delivery
- During Abortion or within 6 weeks after abortion
> Number of deaths happened during an abortion or within 6 weeks after abortion

##### Filters - 
- STart Date and End Date
- District

**Comment by 1t5j0y** [comment]
- [x] Copy place of death report and replace place with period

**Comment by garimadosar5** [comment]
QA Notes- 
- there are total 9 MDs where CBMDR is filled but in report total is 7.

**Comment by 1t5j0y** [comment]
No fix made. Total already showed as 9.

![image.png](https://images.zenhubusercontent.com/5d8a51c647755200010d2fda/120d9e7c-4e09-4920-b363-43146014edff)
