### ISSUE TITLE
[MDSR][Report] No of places visited prior to facility where died - FBMD

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#14]
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362
##### Description
We need to have a district-level report that how many women visit 1,2,3,.... facilities before coming to the facility where they died. The Number of Facilities can be from 0 to 6.
(Page 64 Question 3 .a . i)
##### Columns
 - Number of Places visited 
> Numbers filled in (Page 64 Question 3 .a . i) from 0-6
 - Number of Maternal Deaths
> Count Maternal deaths

Line List - 
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362

##### Filters
- Start date and end date [On Enrolment Date]
- District

### Tech Task

- [x] Kickoff
- [x] Create agg report
- [x] Create new District filter
- [x] Add filters
- [x]  link with linelist

**Comment by nupoorkhandelwal** [comment]
@sachsk   Number of Places visited  -this is not clickable. please check.
