### ISSUE TITLE
[MDSR][UNICEF] Data migration from ODK

### ISSUE THREAD

**Issue by vinayvenu** [OpenCHS/unicef-moha#19]
Form mapping and data import for both forms ( FORM 4 & FORM 5) is done and tested.

 

Before importing the actual data, mapping of location and referral fields need to be corrected.

**Comment by garimadosar5** [comment]
form structure and design have been changed now so we are not doing any data migration. CSV file of the data has been shared with the MDSR Assam team. This communication has been done with the client.

Moving this card to closed.
