### ISSUE TITLE
[MDR] Feedback - Verbal consent form (Form 5)

### ISSUE THREAD

**Issue by charl3sj** [OpenCHS/unicef-moha#2]
- Validation: Date of Investigation > Date of Death
- Probable cause of death options: -APH -PPH -Eclampsia -Puerperal Sepsis -Prolonged Labour -Ruptured Uterus -Septic Abortion -Others (Specify)
---
In Verbal Consent Letter/Form:
* Validation: Date of Investigation > Date of Death

#### Module 1
- 5a) If death is during pregnancy then forms for abortion, intrapartum and postnatal should be blocked
- 5b) If death is during delivery then forms for abortion, and postnatal should be blocked
- III (Q2) - change wording to "Distance of nearest facility providing C Section from the residence of the deceased"
- III (Q3) - Options: -108 -104 inter-facility -Own Vehicle -Hired Vehicle -Others Specify
- IV - Validation: Para can not be more than Gravida . Para+Abortion not more than Gravida. Number of living children not more than Para and Gravida

#### Module 2
- In VII (Q3) - If ans is no, then go to Q6
- In VII (Q4) - If ans is no, then go to Q6
- Show VIII only if ans to Module I - 5d is Yes
- Add missing questions in VIII
- In VIII table, ask for Date of Admission and not Date of referral

**Comment by garimadosar5** [comment]
##### QA Comment -
- Date of death cannot be a future date.
- Module II, question VI and VII are not showing. (Dev note: should show only if Period of Death is during Delivery or during Abortion)
- Module 2, VIII Abortion related death section is showing given in case of Post delivery death. (Possibly Staging env issue)
- Module 3, Question IX.9. Make it multi-select.
- Qus 10b. Module 3. give the option of Image capture.
- Module 3, X.2b. Make it days and Hrs type.
- Module 3. Question X.4 skip is not working properly.
- Qus XI. Open Narrative. Give an option of Capturing the image. In case they have written the narrative on paper.
 
-- If answer to question "Do you agree to participate in this interview" is NO. It should not ask any question after that. Currently it ask BACKGROUND INFORMATION and IV- Write GPLA.
