### ISSUE TITLE
[MDSR] ICD 10 classification - Form 5

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#3]
https://drive.google.com/file/d/1JgHZ65DLHvuGV-MydTQZZgN_fergLGap/view?usp=sharing

https://drive.google.com/drive/u/0/folders/1UQS1IIxmwksONoaoWnd9tBC1gF0j8qF9 - Page No- 92,93, 94

- data Type - Multiselect

##### QA Comments - 
- "Cause of death" question is asking at the beginning of the form only.

**Comment by charl3sj** [comment]
> "Cause of death" question is asking at the beginning of the form only.


fixed
