### ISSUE TITLE
[MDSR] Move implementation (bundle) from org 1 to Unicef - Moha

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#30]
**TASKS** - 

Steps--

Remove the dependency from DB for org 1.

1. Add individual subject type

2. Only concepts and subject type, will have to be added( directly upload the common concepts). 
Create script to add common concepts to the implementation.

FOR LATER - 
- Move existing rules to new rules.

**Comment by nupoorkhandelwal** [comment]
Steps--

Remove the dependency from DB for org 1.

1. Add individual subject type

2. Only concepts and subject type, will have to be added( directly upload the common concepts).
