### ISSUE TITLE
[MDSR][Report] Number of maternal deaths reported at transit

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#35]
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362
##### Description - 
The number of maternal deaths reported at transit. District wise list.

##### Columns - 
- S. No.
- District
- Number of maternal deaths Reported at transit
> Total number of maternal deaths reported at transit
- % of maternal deaths at home
> formula: (Number of MD at transit/total number of maternal deaths

1 | Number of Maternal deaths at trasit | Count all the cases from FORM 1 where QUS 12 = 3 (Transit) and QUS 13 is != None
-- | -- | --

Line List - 
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362

##### Filter - 
- Start Date and End Date - On Enrolment Date

**Comment by 1t5j0y** [comment]
- [x] Create reusable common linelist
- [x] Aggregate - Query form 1 for deaths that occurred in transit
- [x] Link to common linelist

**Comment by 1t5j0y** [comment]
Dev box feedback:
- [x] Show all districts even with 0 counts (Pending confirmation)
- [x] Don't show serial number for total
- [x] Show percentage as 0% instead of blank

**Comment by garimadosar5** [comment]
QA Notes - 
- When the date filter is applied. districts do not appear where deaths are zero.
refer - FBMD Report

**Comment by 1t5j0y** [comment]
Fixed.
