### ISSUE TITLE
[MDSR] Facility/Address Hierarchy Implementation.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#4]
https://docs.google.com/spreadsheets/d/1AvnNwmT5RoSmKcVnr7DXHU2ajvdK0QXrznYqcOhMKlk/edit#gid=1806528925

**Urban and Rural Hierarchies**
Urban and Rural have different hierarchies of facility with assignable address at different levels. 
Urban : District -> City/town -> UPHC/UCHC
Rural : District -> Block -> PHC -> Subcentre

**For facility deaths -** 
- Facility-based user will know the address till the block. (In Registration or form 4)
- And then the rest of the address will be filled in form 5 by Community/Catchment user.

**For community-based death -** 
Same as Facility based deaths.

Currently, this is dependent on platform feature. So, we will have facility based users' setup for now and when the platform feature is done then location can be setup.

**Comment by nupoorkhandelwal** [comment]
MDSR has 2 address levels - District and Block. 
- Block is the lowest address level that would be assigned to all subjects. 
- Facilities are defined and have an address similar to subjects. 
- Users have 2 types of operating scope - ByCatchment or ByFacility
- User can be mapped to one or more facilities (ideally one facility)
- If the subject is created by facility based user then server assigns that facility to the subject in addition to the  block (lowestAddressLevel). 
- When a facility based user syncs all the individuals with that facility are synced to him.

**Comment by nupoorkhandelwal** [comment]
Done till now--

Created Urban and Rural Hierarchies
Added a facility and facility user

@nupoorkhandelwal there are three cases, showing in the list. test lastname, Heena Khand and Rami Singh. but earlier we did not enrolled any woman from facility. so it should not show the cases.
