### ISSUE TITLE
[MDSR][Report] Heat Map of Maternal Deaths by District

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#40]
a heat map with the number of MDs reported in a district.

Refer to:
https://reporting.avniproject.org/question/444

- We will have estimated deaths and actual deaths from all the districts which need to be displayed as a district-wise heat map for Assam.

**Comment by 1t5j0y** [comment]
- [ ] Determine configurable mechanism to store estimated deaths per district.
- [ ] Query to fetch estimate and actual counts
- [x] Define district co-ordinates in paths format required by Jasper
- [ ] Define style for actual death counts
- [ ] Define style for actual as a percentage of estimated
- [ ] Parameterize application of style

**Comment by 1t5j0y** [comment]
Changed approach to use Metabase for this.

Created 2 reports:
https://reporting.avniproject.org/question/1376
https://reporting.avniproject.org/question/1377

**Comment by garimadosar5** [comment]
@1t5j0y 
Putting it on hold. As we need to see if we can put it on jasper.
