### ISSUE TITLE
[MDSR] Form 5 create address heirarchy

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#44]
https://drive.google.com/drive/folders/1w2t63ZrFAccQWNC2J0QPC2pk7ICYCAWv

Form 5
**FEG -** For investigation of maternal deaths
**FE -** State, district etc.etc..... Make it 
**Rural -** 
District
Block
PHC 
Subcenter

**Urban-**
District
City/Town
UPHC/UCHC

- It will require a dropdown. (It will be done later)

**Comment by sachsk** [comment]
@garimadosar5 Dropdown feature not available.

**Comment by garimadosar5** [comment]
QA Notes - 
- Subcenters are not available in the address and it is throwing error.
![Screenshot_2020-10-12-11-58-33-34.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/e15dadea-a7eb-4961-ab5a-9778e4af489e)
