### ISSUE TITLE
[MDSR] Create a report with all high level indicators.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#46]
User wants a report with all the indicators in one report so that they do not have to merge all the report to do the analysis.

**Create a report with the following columns -** 

District
1. Total deaths reported
2. CBMD Reviews
     CBMD Review %
3. FBMD Review
    FBMD Review %
4. Maternal Deaths at Home
5. Maternal Deaths in transit
6. CBMD Delay - I
    CBMD Delay - 2
    CBMD Delay - 3
7. FBMD Delay - I
    FBMD Delay - 2
    FBMD Delay - 3
8. Underlying factors for maternal deaths - FBMD

These reports are already there, we just need to create one more report with all the indicator together.

**Comment by sachsk** [comment]
needs to discuss some points with garima

**Comment by garimadosar5** [comment]
QA Notes - 
- Show % values till 1 decimal place. for all the indicators.

**Comment by sachsk** [comment]
fixed
