### ISSUE TITLE
[MDSR] Move org to prod for Pilot.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#49]
Create a Training Org also.

Org Name - MDSR -MOHA

Checklist
- [x] Org Creation
- [x] Training Org
- [x] Location Upload 
- [x] User Creation
- [x] Facility Upload
- [x] Facility User Creation

Location Document - https://docs.google.com/spreadsheets/d/17OSrRzxC1nOcgnzxbvb8QjL2wZsFJFAu/edit#gid=1074780234

**Comment by sachsk** [comment]
@garimadosar5  created new org
user id: qa_user@mdsrmoha
password: password

Training org
id: qa_user@mdsr_moha_training
password: password
