### ISSUE TITLE
[MDSR] Changes in form 4 and Form 5

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#5]
Ref Doc - https://drive.google.com/drive/u/0/folders/1UQS1IIxmwksONoaoWnd9tBC1gF0j8qF9
Form 4 - 
3-a-i) No of places visited prior - Increase the limit from 3 to 6. -- **Done**
Also, the set of question in the table needs to asked 6 times (based on the number filled for 3.a.i). -- **DONE**

Form 5 - 
Table 1. Page 81 and Table 2. Page 87
Set of Questions from the table is being asked 3 times make it 6 times.
Section II - Profile of deceased woman - Add a question "Age at the time of first pregnancy" after "Age at marriage". - **DONE**

- In form 4 page No 64 (table), that comments need to be incorporated in form - 5 table 1 (page 81) and table 2 (page 87).

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  

 In form 4 page No 64 (table), that comments need to be incorporated in form - 5 table 1 (page 81) and table 2 (page 87).

What does this comment mean??

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 
QA Notes - 
- In Form 5, Table1 (Page 81) and Table 2 (Page 87) is not showing. - **DONE**
- In form 4, Table for referral (Page 64). For facility 4 onwards, questions are different than facility 3 and before 3.
All the question will be the same facility 1 onwards.

**Comment by garimadosar5** [comment]
QA Notes - 

1. Form4 table for the referral - Page no 64
Facility 4 onwards - Other referral reason, other staff attended, other transport used and other treatment is given, skip logic is not working for these questions. - **DONE**
2. The app is crashing on last page group "Case summary". - **NOT DONE**

3. Form5 Table for the referral - Page 81 and 87.  - **DONE**
Other referral reason, other staff attended, other transport used and other treatment is given, these questions are not showing if 'Other' option is selected as an answer to the respective question.

4. Sync is failing. - **DONE**
![Screen Shot 2019-11-29 at 12.51.42 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/8b616842-df50-4fd1-82c8-5c727446dc60)

**Comment by garimadosar5** [comment]
@sachsk 

Form 4 is crashing on UAT.
