### ISSUE TITLE
[MDSR] Make all the visits general encounters

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#52]
- Put Form 1: Notification form in Registration.
- form 4,5 and 6 in the general encounter.
- Visit scheduling will be the same.
- Changes in reports based on these changes.

### App

- [x] App Changes
     - [x] Delete existing data
     - [x] Upload mdsrcg-uat bundle

#### Reports
- [x] Update view in reports
- [x] Import mdsrcg-uat bundle

**Comment by sachsk** [comment]
Please use this apk for testing:
 https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-x86-1a38-2020-11-02-16-35-43.apk
