### ISSUE TITLE
[MDSR][MOHA] Create a new org and upload CG bundle.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#53]
- [x] Create a new org as MDSR-MOHA UAT
- [x] Upload MDSRCG - UAT bundle with some changes.
1. Form 1 - Permanent Address, replace Chattisgarh with Assam
2. add 104 Ambulance service wherever ambulance is asked.
- [x] Upload Assam locations.
https://docs.google.com/spreadsheets/d/17OSrRzxC1nOcgnzxbvb8QjL2wZsFJFAu/edit#gid=1074780234

**Comment by garimadosar5** [comment]
Status - [20-04-2021] Facility Upload is pending.

**Comment by sachsk** [comment]
Org name:- MDSR MOHA UAT

**Comment by garimadosar5** [comment]
QA Notes - 
Locations are not proper. In reg, it is showing PHC/SC etc. and the first page is not going forward.
for CG- Form 5 also has address hierarchy.

**Comment by sachsk** [comment]
Facility user : assam_medical_college@mdsrmoha_uat

**Comment by garimadosar5** [comment]
**QA Notes -** 
**- Reg form**
- Gender - Only female should be there.
- Demographic details - In permanent address if "Different from current but within Assam" is selected then In DISTRCT only one district is showing that is in the catchment.
-
