### ISSUE TITLE
[MDSR][Report] FBMD Review

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#6]
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362
##### Description - 
Number of deaths for which Facility-based maternal death review (FBMDR) have been conducted (put the percentage in a bracket )

##### Columns - 
- S. No.
- District
- Number of Facility-based maternal deaths Reported 
> Total number of Form 4 scheduled 
- Number of FBMD Review done
> Number of Form 4 filled
- % of FBMD review done 
> formula: (Number of FBMD Review done/Number of Facility-based maternal deaths)*100

Line List
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362

##### Filter - 
- Start and End Date - On Enrolment Date

**Comment by 1t5j0y** [comment]
- [x] Aggregate - Query count of 'Form filled in' = Facility in form 1 as scheduled form 4 visit
- [x] Aggregate - left join form 4 view on enrolment id and check count of encounter_date_time not null
- [x] Link to common linelist

**Comment by 1t5j0y** [comment]
Form 4 getting scheduled again on edit of enrolment and affecting the logic.
Pending clarification on whether all districts should be shown.
