### ISSUE TITLE
[MDSR][Report] CBMD Review

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#7]
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362
##### Description - 
Number of deaths for which Community-based maternal death review (CBMDR) have been conducted (put the percentage in a bracket )

##### Columns - 
- S. No.
- District
- Number of Community-based maternal deaths Review form scheduled 
> Total number of Form 5 scheduled (only for community-based MDs)
- Number of CBMD Review done
> Number of Form 5 filled out of schedule
- % of CBMD review done 
> formula: (Number of CBMD Review done/Number of Facility-based maternal deaths)*100

Line list - 
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362

##### Filter - 
- Start Date and End Date - On Enrolment Date

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Total row is missing in this. - **DONE**
(we are adding total in all other aggregates).
- form % calculation - Barpeta District. % is 55.0%. either put 1/2 digit after decimal or put the round value then remove the decimal. - **DONE**
- Line List - Column, "Date and time of death", time is not showing right. Case Divya Kumari - Time is 10:49 in the app and in report showing - 23/06/20 05:30 - **DONE**
- Add all the district in the list. - **DONE**
- It gives error when date filter is applied.
![Screen Shot 2020-09-11 at 11.07.36 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f13a94a9-dc65-44f2-9a40-ab4c38673dee)

**Comment by garimadosar5** [comment]
QA Notes - 
- error message while clicking on aggregate number
![Screen Shot 2020-09-11 at 11.52.31 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/5492f10a-33dc-4b96-8169-93024d2b0693)

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 Which aggregate number. I dont see any error.
