### ISSUE TITLE
[MDSR][Report] Pie chart for Place of death - CBMD

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-moha#9]
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362
##### Description - 
List/Pie chart of the deaths happened at different places from Community based Maternal deaths (Section I - Question 6, Place of death).

##### Data Required - 
- Home
> Number deaths happened at Home
- Sub-district Hospital
> Number deaths happened at sub-district hospital
- Sub-Health Centre
> Number deaths happened at the sub-health centre
- District Hospital
> Number deaths happened at district Hospital
- PHC
> Number deaths happened at PHC
- Private Hospital
> Number deaths happened at Private Hospital
- CHC
> Number deaths happened at CHC
- In Transit
> Number deaths happened in-transit
- Other
> Number of deaths happened at other places.

line list - 
https://docs.google.com/spreadsheets/d/1hr-0OGn47OuqHtpjPAs2ocn8p64mSjjkuyQ9pw99t80/edit#gid=92888362

##### Filter - 
- Start Date and End Date
- District

**Comment by 1t5j0y** [comment]
- [x] Query possible values for place of death of concept and left join to actual form 5 answers.Calculate counts and percentages.
- [x] Pie chart
- [x] Link to linelist

**Comment by 1t5j0y** [comment]
Dev box feedback:
- [x] Update order of place of death to be same as form order
